name = "backend"
main = "src/routes/app.ts"
compatibility_date = "2024-12-30"

# compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiOTM1MzIwOGItOGI5Yi00OTU3LWJhY2QtY2VkMDQ4MDE1ZTQzIiwidGVuYW50X2lkIjoiYTk5ZmY1YmE2ZTc5OTIwNDczZWQ1Y2QzZDVjZGNiY2YwY2E4NjVlOTlkMTgxMjI1MjIzODQ4ZGY3ODQxNTUzMCIsImludGVybmFsX3NlY3JldCI6IjUyNzA1ZjAwLWYzM2MtNDhkNC05OTZlLTU2NzY4YzZmOTU3MyJ9.92aRuZBiUgkJR40Uv4v4HuXp9PQX6Uqal_XRUgYKMGA"
JWT_SECRET="mediumBlog"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1